namespace Launcher.KeyMapping {
    public enum KeyEvent {
        FLIP_DISPLAY,
        FLIP_SANDBOX,
        OPEN_PROJECTOR_PARAMS,
        OPEN_CALIBRATION,
        OPEN_SANDBOX_CALIBRATION,
        RESET,
        OPEN_NEXT_GAME,
        OPEN_PREV_GAME,
        BACK,
        SWITCH_MODE,
        SHOW_UI,
        UP,
        DOWN,
        LEFT,
        RIGHT,
        ZOOM_IN,
        ZOOM_OUT,
        ANGLE_INC,
        ANGLE_DEC,
        WIDE_PLUS,
        WIDE_MINUS,
        SET_DEPTH_ZERO,
        SET_DEPTH_MIN,
        SET_DEPTH_MAX,
        EXIT
    }
}